name: learn-github-actions
on: [push]
jobs:
  testbuild:
    runs-on: windows-2022
    steps:
      - name: Install Power Apps CLI
        shell: pwsh
        run: Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile powerapps.msi;  Start-Sleep -Seconds 120; msiexec /i .\powerapps.msi /quiet
      - name: Test Power Apps CLI
        shell: pwsh
        run: pac
