name: learn-github-actions
on: [push]
jobs:
  testbuild:
    runs-on: windows-2022
    steps:
      - name: Install Power Apps CLI
        shell: pwsh
        run: Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile .\powerapps.msi; Start-Process "msiexec" "/i powerapps.msi /qn /l*! .\log.txt" -NoNewWindow -PassThru; Start-Sleep -Seconds 60
      - name: Test Power Apps CLI
        shell: pwsh
        run: pac
