name: learn-github-actions
on: [push]
jobs:
  testbuild:
    runs-on: windows-2022
    steps:
      - name: Install Power Apps CLI
        shell: pwsh
        run: Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile .\powerapps.msi; $proc = Start-Process "msiexec" "/i powerapps.msi /qn /l*! .\log.txt" -NoNewWindow -PassThru; $proc.WaitForExit() ; Get-Content log.txt
      - name: Test Power Apps CLI
        shell: pwsh
        run: C:\Users\runneradmin\AppData\Local\Microsoft\PowerAppsCLI\pac.cmd
